apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dygi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-dygi@sha256:a31869493fe72e2fff0ccb89ed98829c351372476574f66e6f9f1aa875087fd6
        name: my-nodejs
        resources: {}
status: {}
